import type { Product, Order, Seller, Analytics, Review } from './types'

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Premium UI Kit for Figma',
    description: 'A comprehensive UI kit with 500+ components, perfect for web and mobile design projects.',
    price: 750000,
    category: 'Design Templates',
    imageUrl: '/placeholder-product.jpg',
    sellerId: 'seller-1',
    sellerName: 'DesignStudio Pro',
    rating: 4.8,
    reviewCount: 234,
    downloadCount: 1520,
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Complete React Course',
    description: 'Master React from beginner to advanced with real-world projects and best practices.',
    price: 1200000,
    category: 'Online Courses',
    imageUrl: '/placeholder-product.jpg',
    sellerId: 'seller-2',
    sellerName: 'CodeMaster Academy',
    rating: 4.9,
    reviewCount: 892,
    downloadCount: 3420,
    featured: true,
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    title: 'E-commerce Starter Template',
    description: 'Launch your online store quickly with this production-ready Next.js template.',
    price: 1950000,
    category: 'Code Templates',
    imageUrl: '/placeholder-product.jpg',
    sellerId: 'seller-1',
    sellerName: 'DesignStudio Pro',
    rating: 4.7,
    reviewCount: 156,
    downloadCount: 890,
    featured: true,
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    title: 'Digital Marketing eBook',
    description: 'Learn proven strategies to grow your business online with this comprehensive guide.',
    price: 450000,
    category: 'E-Books',
    imageUrl: '/placeholder-product.jpg',
    sellerId: 'seller-3',
    sellerName: 'Marketing Gurus',
    rating: 4.5,
    reviewCount: 445,
    downloadCount: 2100,
    featured: false,
    createdAt: '2024-01-25',
  },
  {
    id: '5',
    title: 'Icon Pack - 1000+ Icons',
    description: 'Beautiful hand-crafted icons in multiple formats for your next project.',
    price: 600000,
    category: 'Design Templates',
    imageUrl: '/placeholder-product.jpg',
    sellerId: 'seller-4',
    sellerName: 'IconArtist',
    rating: 4.6,
    reviewCount: 312,
    downloadCount: 1850,
    featured: false,
    createdAt: '2024-02-05',
  },
  {
    id: '6',
    title: 'SaaS Dashboard Template',
    description: 'A modern dashboard template with analytics, charts, and user management built-in.',
    price: 1350000,
    category: 'Code Templates',
    imageUrl: '/placeholder-product.jpg',
    sellerId: 'seller-2',
    sellerName: 'CodeMaster Academy',
    rating: 4.8,
    reviewCount: 178,
    downloadCount: 920,
    featured: true,
    createdAt: '2024-03-01',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    products: [{ product: mockProducts[0], quantity: 1 }],
    total: 750000,
    status: 'completed',
    createdAt: '2024-03-15T10:30:00Z',
    customerId: 'cust-1',
    customerEmail: 'john@example.com',
  },
  {
    id: 'ORD-002',
    products: [{ product: mockProducts[1], quantity: 1 }, { product: mockProducts[3], quantity: 1 }],
    total: 1650000,
    status: 'completed',
    createdAt: '2024-03-14T15:45:00Z',
    customerId: 'cust-2',
    customerEmail: 'jane@example.com',
  },
  {
    id: 'ORD-003',
    products: [{ product: mockProducts[2], quantity: 1 }],
    total: 1950000,
    status: 'pending',
    createdAt: '2024-03-16T09:15:00Z',
    customerId: 'cust-3',
    customerEmail: 'mike@example.com',
  },
]

export const mockSeller: Seller = {
  id: 'seller-1',
  name: 'DesignStudio Pro',
  email: 'contact@designstudiopro.com',
  avatar: '/placeholder-avatar.jpg',
  bio: 'We create beautiful digital products that help businesses grow. Specializing in UI/UX design and web templates.',
  totalSales: 231300000,
  totalProducts: 24,
  rating: 4.8,
  joinedAt: '2023-06-15',
}

export const mockAnalytics: Analytics = {
  totalRevenue: 368700000,
  totalOrders: 342,
  totalProducts: 24,
  averageOrderValue: 1078050,
  revenueByMonth: [
    { month: 'Jan', revenue: 31500000 },
    { month: 'Feb', revenue: 36750000 },
    { month: 'Mar', revenue: 48000000 },
    { month: 'Apr', revenue: 42000000 },
    { month: 'May', revenue: 52500000 },
    { month: 'Jun', revenue: 61500000 },
    { month: 'Jul', revenue: 57000000 },
    { month: 'Aug', revenue: 63000000 },
    { month: 'Sep', revenue: 58500000 },
    { month: 'Oct', revenue: 67500000 },
    { month: 'Nov', revenue: 78000000 },
    { month: 'Dec', revenue: 72450000 },
  ],
  topProducts: [
    { name: 'Premium UI Kit', sales: 1520 },
    { name: 'E-commerce Template', sales: 890 },
    { name: 'Dashboard Kit', sales: 720 },
    { name: 'Icon Pack', sales: 650 },
    { name: 'Mobile App Kit', sales: 480 },
  ],
}

export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    productId: '1',
    customerId: 'cust-1',
    customerName: 'John D.',
    rating: 5,
    comment: 'Excellent quality! The components are well-organized and easy to customize.',
    createdAt: '2024-03-10T14:30:00Z',
  },
  {
    id: 'rev-2',
    productId: '1',
    customerId: 'cust-2',
    customerName: 'Sarah M.',
    rating: 4,
    comment: 'Great kit, saved me a lot of time. Would love more dark mode variants.',
    createdAt: '2024-03-08T09:15:00Z',
  },
  {
    id: 'rev-3',
    productId: '2',
    customerId: 'cust-3',
    customerName: 'Mike R.',
    rating: 5,
    comment: 'Best React course I have taken. Very comprehensive and practical.',
    createdAt: '2024-03-12T16:45:00Z',
  },
]

export const categories = [
  'All',
  'Design Templates',
  'Code Templates',
  'Online Courses',
  'E-Books',
  'Graphics',
  'Audio',
]
